octo extension 23 June 2025

diff --git a/docker/DockerfileOcto b/docker/DockerfileOcto
--- a/docker/DockerfileOcto
+++ b/docker/DockerfileOcto
@@ -30,10 +30,13 @@ RUN dnf install -q -y --allowerasing --nobest \
   dnf update -y && dnf clean all
 
 ENV EXTERNAL_SOURCE_NESTED=.
-ENV CONTAINER_SOURCE=/opt/app-root/src
+ENV CONTAINER_SOURCE=/opt/octo/src
 
 # Env vars
 ENV YARN=$CONTAINER_SOURCE/.yarn/releases/yarn-3.8.7.cjs
+ENV CFLAGS="-O2 -fno-lto"
+ENV CXXFLAGS="-O2 -fno-lto"
+ENV MAKEFLAGS=-j1
 
 WORKDIR $CONTAINER_SOURCE/
 COPY $EXTERNAL_SOURCE_NESTED/.yarn ./.yarn
@@ -58,6 +61,7 @@ COPY $EXTERNAL_SOURCE_NESTED/package.json ./package.json
 
 # unpack headers from tarball (includes openssl headers not present in /usr/include/node) - see RHIDP-6755 for why we need this upstream
 COPY $EXTERNAL_SOURCE_NESTED/.nvm/ .
+
 RUN NODE_HEADERS_VERSION=$(node --version); echo "=== Install node headers $NODE_HEADERS_VERSION from tar.gz ==="; \
   if [[ ! -f releases/node-${NODE_HEADERS_VERSION}-headers.tar.gz ]]; then \
   echo "[ERROR] Base image includes nodejs $NODE_HEADERS_VERSION but could not find releases/node-${NODE_HEADERS_VERSION}-headers.tar.gz to install!"; \
@@ -72,7 +76,7 @@ RUN NODE_HEADERS_VERSION=$(node --version); echo "=== Install node headers $NODE
 # Increase timeout for yarn install
 RUN "$YARN" config set httpTimeout 600000
 
-RUN echo "=== YARN INSTALL ==="; FAILED=0; "$YARN" install --immutable; \
+RUN echo "=== YARN INSTALL ==="; FAILED=0; CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" "$YARN" install --immutable; \
   for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
   (( FAILED = FAILED + 1 )); \
   echo; echo $d; \
@@ -88,7 +92,7 @@ COPY $EXTERNAL_SOURCE_NESTED ./
 
 RUN git config --global --add safe.directory ./
 # Upstream only
-RUN rm app-config.yaml && mv app-config.example.yaml app-config.yaml
+RUN rm -rf dynamic-plugins/* && rm -rf dynamic-plugins-octo && rm -rf octo-plugins-root
 
 # Downstream only - replace midstream build-metadata.json with the version from downstream (where we include the midstream SHA)
 # COPY packages/app/src/build-metadata.json ./packages/app/src/
@@ -100,14 +104,34 @@ RUN \
   -e "s/(\"Last Commit\": \"(.+)\")/\1, \"Build Time\": \"$now\"/" && \
   cat packages/app/src/build-metadata.json; echo
 
-# suppress git warnings about dubious ownership in repository at '/opt/app-root/src' when building
+# suppress git warnings about dubious ownership in repository at '/opt/octo/src' when building
 RUN echo "=== YARN BUILD ==="; FAILED=0; \
-  git config --global --add safe.directory /opt/app-root/src; \
+  git config --global --add safe.directory /opt/octo/src; \
   "$YARN" build || true; \
   for d in $(find . -name yarn-install.log); do \
   (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}; \
   done; \
   if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
+
+WORKDIR $CONTAINER_SOURCE/dynamic-plugins-octo
+
+RUN echo "=== DYNAMIC PLUGIN YARN INSTALL ==="; FAILED=0; "$YARN" install --immutable; \
+  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
+  (( FAILED = FAILED + 1 )); \
+  echo; echo $d; \
+  echo "!!! DYNAMIC PLUGIN YARN INSTALL FAILED !!!"; \
+  cat ${d}/build.log; \
+  fi; done; \
+  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
+
+RUN echo "=== EXPORT DYNAMIC PLUGINS ==="; FAILED=0; \
+  "$YARN" export-dynamic || true; \
+  for d in $(find . -name yarn-install.log); do \
+  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}; \
+  done; \
+  if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
+
+RUN echo "=== YARN COPY DYNAMIC PLUGINS in $(pwd) ==="; "$YARN" copy-dynamic-plugins dist
 
 WORKDIR $CONTAINER_SOURCE
 
@@ -127,10 +151,11 @@ COPY --from=build \
 # unpack and remove tarballs
 ENV TARBALL_PATH=./packages/backend/dist
 RUN tar xzf "$TARBALL_PATH"/skeleton.tar.gz; tar xzf "$TARBALL_PATH"/bundle.tar.gz; \
-  rm -f "$TARBALL_PATH"/skeleton.tar.gz "$TARBALL_PATH"/bundle.tar.gz
+    rm -f "$TARBALL_PATH"/skeleton.tar.gz "$TARBALL_PATH"/bundle.tar.gz
 
 # Copy app-config files needed in runtime
 COPY $EXTERNAL_SOURCE_NESTED/app-config.yaml ./
+COPY $EXTERNAL_SOURCE_NESTED/app-config.octo.yaml ./
 
 # Hackaround: create library symlinks to build: isolated-vm node-gyp better-sqlite cpu-features
 # TODO is this still needed? maintaining it over time will be a chore if the .so files change
@@ -151,12 +176,12 @@ RUN echo "=== YARN WORKSPACES FOCUS ==="; FAILED=0; "$YARN" workspaces focus --a
   fi; done; \
   if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
-RUN \
+RUN mkdir .rbac && \
   # delete all the nested .npmrc files and set default values
   find . -type f -name .npmrc -exec rm -Rf {} \; && \
   # reset npm config to the default registry and absolute path to .pem file
   npm config set registry=https://registry.npmjs.org/ && \
-  npm config set cafile /opt/app-root/src/registry-ca.pem
+  npm config set cafile /opt/octo/src/registry-ca.pem
 
 # Stage 5 - Build the runner image
 # https://registry.access.redhat.com/ubi9/nodejs-22-minimal
@@ -164,18 +189,20 @@ FROM registry.access.redhat.com/ubi9/nodejs-22-minimal:9.6-1749542063 AS runner
 USER 0
 
 ENV EXTERNAL_SOURCE_NESTED=.
-ENV CONTAINER_SOURCE=/opt/app-root/src
+ENV CONTAINER_SOURCE=/opt/octo/src
 WORKDIR $CONTAINER_SOURCE/
 
 # Install techdocs dependencies using requirements files
 # hadolint ignore=DL3013,DL3041,SC2086
 COPY "$EXTERNAL_SOURCE_NESTED"/python/ ./python
+COPY "$EXTERNAL_SOURCE_NESTED"/.rbac/ ./.rbac/
+
 RUN microdnf install -y python3.11 python3.11-pip python3.11-devel make cmake cpp gcc gcc-c++ skopeo 1>/dev/null 2>&1; \
   alternatives --install /usr/bin/python python /usr/bin/python3.11 1 && \
   alternatives --install /usr/bin/pip pip /usr/bin/pip3.11 1 && \
   # fix ownership for pip install folder
-  mkdir -p /opt/app-root/src/.cache/pip && chown -R root:root /opt/app-root && \
-  # ls -ld /opt/ /opt/app-root /opt/app-root/src/ /opt/app-root/src/.cache /opt/app-root/src/.cache/pip || true; \
+  mkdir -p /opt/octo/src/.cache/pip && chown -R root:root /opt/octo && \
+  # ls -ld /opt/ /opt/octo /opt/octo/src/ /opt/octo/src/.cache /opt/octo/src/.cache/pip || true; \
   pushd "$EXTERNAL_SOURCE_NESTED"/python/ >/dev/null && \
   set -e; \
   python3.11 -V; pip3.11 -V; \
@@ -190,9 +217,6 @@ COPY --from=cleanup --chown=1001:1001 $CONTAINER_SOURCE/ ./
 # Downstream only - copy from build, not cleanup stage
 # COPY --from=build --chown=1001:1001 "$CONTAINER_SOURCE"/ ./
 
-# Clean dynamic-plugins
-RUN rm -rf ./dynamic-plugins/* && rm -rf ./dynamic-plugins-octo && rm -rf ./dynamic-plugins-root
-
 # RHIDP-4220 - make Konflux preflight and EC checks happy - [check-container] Create a directory named /licenses and include all relevant licensing
 COPY $EXTERNAL_SOURCE_NESTED/LICENSE /licenses/
 
@@ -202,15 +226,15 @@ COPY $EXTERNAL_SOURCE_NESTED/catalog-entities/marketplace /marketplace/catalog-e
 # Copy script to gather dynamic plugins; copy embedded dynamic plugins to root folder; fix permissions
 COPY docker/install-dynamic-plugins.py docker/install-dynamic-plugins.sh ./
 RUN chmod -R a+r ./install-dynamic-plugins.py; \
-  chmod -R a+rx ./install-dynamic-plugins.sh
+    chmod -R a+rx ./install-dynamic-plugins.sh
 
 # The existence of the index.html.tmpl tells Backstage to take that file and load it into memory, inject the needed appConfig (instead of writing
 # it into a random *.chunk.js file, and then serve that file from memory so that we can set the readOnlyRootFilesystem: true option for
 # the container.
-RUN ln -s /opt/app-root/src/packages/app/dist/index.html /opt/app-root/src/packages/app/dist/index.html.tmpl
+RUN ln -s /opt/octo/src/packages/app/dist/index.html /opt/octo/src/packages/app/dist/index.html.tmpl
 
 # Fix for https://issues.redhat.com/browse/RHIDP-728
-RUN mkdir -p /opt/app-root/src/.npm; chown -R 1001:1001 /opt/app-root/src/.npm
+RUN mkdir -p /opt/octo/src/.npm; chown -R 1001:1001 /opt/octo/src/.npm
 
 # The fix-permissions script is important when operating in environments that dynamically use a random UID at runtime, such as OpenShift.
 # The upstream backstage image does not account for this and it causes the container to fail at runtime.
